# Generated by Django 5.2.16 on 2026-07-13 13:04

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeePerformanceReview',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('department', models.CharField(blank=True, db_index=True, max_length=80)),
                ('designation', models.CharField(blank=True, max_length=120)),
                ('review_cycle', models.CharField(choices=[('Q1 2026', 'Q1 2026'), ('Q2 2026', 'Q2 2026'), ('Q3 2026', 'Q3 2026'), ('Q4 2026', 'Q4 2026')], db_index=True, max_length=20)),
                ('review_stage', models.CharField(choices=[('draft', 'Draft'), ('manager_review', 'Manager Review'), ('hr_review', 'HR Review'), ('finalized', 'Finalized')], db_index=True, default='draft', max_length=30)),
                ('goals_assigned', models.PositiveSmallIntegerField(default=0)),
                ('goals_completed', models.PositiveSmallIntegerField(default=0)),
                ('kpi_score', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('task_completion', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('quality_score', models.DecimalField(decimal_places=1, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('attendance_score', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('status', models.CharField(choices=[('top_performer', 'Top Performer'), ('exceeds_expectations', 'Exceeds Expectations'), ('meets_expectations', 'Meets Expectations'), ('needs_improvement', 'Needs Improvement'), ('promotion_eligible', 'Promotion Eligible'), ('archived', 'Archived')], db_index=True, default='meets_expectations', max_length=40)),
                ('last_review_date', models.DateField()),
                ('next_review_date', models.DateField()),
                ('manager_notes', models.TextField()),
                ('improvement_plan', models.TextField()),
                ('promotion_readiness', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('attrition_risk', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], db_index=True, default='low', max_length=20)),
                ('recommended_training', models.JSONField(blank=True, default=list)),
                ('metrics', models.JSONField(blank=True, default=list)),
                ('okrs', models.JSONField(blank=True, default=list)),
                ('feedback', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='performance_reviews', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_performance_reviews', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'employee_performance_reviews',
                'indexes': [models.Index(fields=['review_cycle', 'status'], name='employee_pe_review__8c0130_idx'), models.Index(fields=['department', 'status'], name='employee_pe_departm_696871_idx'), models.Index(fields=['next_review_date', 'review_stage'], name='employee_pe_next_re_4d0be8_idx')],
                'constraints': [models.UniqueConstraint(fields=('employee', 'review_cycle'), name='unique_employee_review_cycle')],
            },
        ),
    ]
