# Generated by Django 5.2.16 on 2026-07-08 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileobject',
            name='storage_key',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
