# Generated by Django 5.2.5 on 2026-07-24 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("title", models.CharField(db_index=True, max_length=180)),
                ("message", models.TextField()),
                ("notification_type", models.CharField(choices=[("Info", "Info"), ("Success", "Success"), ("Warning", "Warning"), ("Error", "Error"), ("Assignment", "Assignment"), ("Approval", "Approval"), ("Reminder", "Reminder"), ("Security", "Security"), ("Project", "Project"), ("Finance", "Finance"), ("Support", "Support"), ("HRMS", "HRMS"), ("System", "System")], db_index=True, max_length=30)),
                ("priority", models.CharField(choices=[("Low", "Low"), ("Medium", "Medium"), ("High", "High"), ("Critical", "Critical")], db_index=True, default="Medium", max_length=20)),
                ("action_url", models.CharField(blank=True, max_length=240)),
                ("target_module", models.CharField(blank=True, db_index=True, max_length=80)),
                ("entity_type", models.CharField(blank=True, db_index=True, max_length=120)),
                ("entity_id", models.CharField(blank=True, db_index=True, max_length=80)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("is_broadcast", models.BooleanField(db_index=True, default=False)),
                ("expires_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("recipient", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="notifications", to=settings.AUTH_USER_MODEL)),
                ("deleted_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="deleted_notification_records", to=settings.AUTH_USER_MODEL)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_notification_records", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="updated_notification_records", to=settings.AUTH_USER_MODEL)),
            ],
            options={"db_table": "notifications"},
        ),
        migrations.CreateModel(
            name="CommunicationJob",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("channel", models.CharField(choices=[("Email", "Email"), ("SMS", "SMS"), ("WhatsApp", "WhatsApp"), ("In-App", "In-App")], db_index=True, max_length=20)),
                ("recipient_name", models.CharField(max_length=160)),
                ("recipient_email", models.EmailField(blank=True, max_length=254)),
                ("recipient_mobile", models.CharField(blank=True, max_length=20)),
                ("subject", models.CharField(max_length=180)),
                ("message", models.TextField()),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("status", models.CharField(choices=[("Queued", "Queued"), ("Processing", "Processing"), ("Sent", "Sent"), ("Delivered", "Delivered"), ("Failed", "Failed"), ("Cancelled", "Cancelled")], db_index=True, default="Queued", max_length=20)),
                ("scheduled_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("retry_count", models.PositiveSmallIntegerField(default=0)),
                ("last_error", models.TextField(blank=True)),
                ("deleted_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="deleted_communicationjob_records", to=settings.AUTH_USER_MODEL)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_communicationjob_records", to=settings.AUTH_USER_MODEL)),
                ("notification", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="communication_jobs", to="notifications.notification")),
                ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="updated_communicationjob_records", to=settings.AUTH_USER_MODEL)),
            ],
            options={"db_table": "communication_jobs"},
        ),
        migrations.CreateModel(
            name="NotificationRead",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("read_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("deleted_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="deleted_notificationread_records", to=settings.AUTH_USER_MODEL)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_notificationread_records", to=settings.AUTH_USER_MODEL)),
                ("notification", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="reads", to="notifications.notification")),
                ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="updated_notificationread_records", to=settings.AUTH_USER_MODEL)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="notification_reads", to=settings.AUTH_USER_MODEL)),
            ],
            options={"db_table": "notification_reads"},
        ),
        migrations.AddConstraint(
            model_name="notificationread",
            constraint=models.UniqueConstraint(fields=("notification", "user"), name="unique_notification_read"),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["recipient", "is_broadcast", "is_active", "created_at"], name="notifications_recipie_4d61b8_idx"),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["notification_type", "priority"], name="notifications_notific_d6d7c4_idx"),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["target_module", "notification_type"], name="notifications_target_m_5f1d3f_idx"),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["entity_type", "entity_id"], name="notifications_entity_80f4a0_idx"),
        ),
        migrations.AddIndex(
            model_name="communicationjob",
            index=models.Index(fields=["status", "channel"], name="communication_status_3c3b03_idx"),
        ),
        migrations.AddIndex(
            model_name="communicationjob",
            index=models.Index(fields=["scheduled_at", "status"], name="communication_schedul_4efb0d_idx"),
        ),
        migrations.AddIndex(
            model_name="communicationjob",
            index=models.Index(fields=["recipient_email"], name="communication_recipie_8d8b24_idx"),
        ),
        migrations.AddIndex(
            model_name="communicationjob",
            index=models.Index(fields=["recipient_mobile"], name="communication_recipie_48c3a8_idx"),
        ),
        migrations.AddIndex(
            model_name="notificationread",
            index=models.Index(fields=["user", "read_at"], name="notification_user_rea_9e3d8e_idx"),
        ),
        migrations.AddIndex(
            model_name="notificationread",
            index=models.Index(fields=["notification", "user"], name="notification_notific_18f0b8_idx"),
        ),
    ]
