# Generated by Django 5.2.16 on 2026-08-07 03:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='communicationjob',
            new_name='communicati_status_0b0e2c_idx',
            old_name='communication_status_3c3b03_idx',
        ),
        migrations.RenameIndex(
            model_name='communicationjob',
            new_name='communicati_schedul_2e2e0b_idx',
            old_name='communication_schedul_4efb0d_idx',
        ),
        migrations.RenameIndex(
            model_name='communicationjob',
            new_name='communicati_recipie_d3bfe9_idx',
            old_name='communication_recipie_8d8b24_idx',
        ),
        migrations.RenameIndex(
            model_name='communicationjob',
            new_name='communicati_recipie_52663f_idx',
            old_name='communication_recipie_48c3a8_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_recipie_f6f23d_idx',
            old_name='notifications_recipie_4d61b8_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_notific_5536b0_idx',
            old_name='notifications_notific_d6d7c4_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_target__0dc1a7_idx',
            old_name='notifications_target_m_5f1d3f_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_entity__519f8a_idx',
            old_name='notifications_entity_80f4a0_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationread',
            new_name='notificatio_user_id_159658_idx',
            old_name='notification_user_rea_9e3d8e_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationread',
            new_name='notificatio_notific_b051ae_idx',
            old_name='notification_notific_18f0b8_idx',
        ),
        migrations.AlterField(
            model_name='communicationjob',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='communicationjob',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='communicationjob',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notificationread',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notificationread',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notificationread',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_records', to=settings.AUTH_USER_MODEL),
        ),
    ]
