# Generated by Django 5.2.16 on 2026-07-08 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=80, unique=True)),
                ('prefix', models.CharField(max_length=20)),
                ('current_value', models.PositiveBigIntegerField(default=0)),
                ('padding', models.PositiveSmallIntegerField(default=4)),
            ],
            options={
                'db_table': 'core_sequences',
                'indexes': [models.Index(fields=['code'], name='core_sequen_code_dcc0b5_idx')],
            },
        ),
    ]
