# Generated by Django 5.2.16 on 2026-07-22 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_tds_period_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalpolicy',
            name='second_approver_role',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='approvalpolicy',
            name='sla_hours',
            field=models.PositiveSmallIntegerField(default=8),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='approval_level',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='budget_status',
            field=models.CharField(default='Not Applicable', max_length=40),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='compliance_check',
            field=models.CharField(default='Clear', max_length=20),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='current_approver_role',
            field=models.CharField(blank=True, db_index=True, max_length=80),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='department',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='due_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='duplicate_check',
            field=models.CharField(default='Clear', max_length=20),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='events',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='finance.approvalpolicy'),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='requester_name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='requester_role',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='risk',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], db_index=True, default='low', max_length=20),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='second_approver_role',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='approvalpolicy',
            name='max_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='approvalrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('clarification_required', 'Clarification Required'), ('hold', 'Hold'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=30),
        ),
        migrations.AddIndex(
            model_name='approvalpolicy',
            index=models.Index(fields=['module', 'min_amount', 'max_amount'], name='approval_po_module_201453_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['current_approver_role', 'status'], name='approval_re_current_eeea32_idx'),
        ),
    ]
