# Generated by Django 5.2.16 on 2026-07-22 15:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_approval_workflow_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='financeaccesspolicy',
            name='approval_limit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='financeaccesspolicy',
            name='audit_access',
            field=models.CharField(default='No Access', max_length=30),
        ),
        migrations.AddField(
            model_name='financeaccesspolicy',
            name='can_archive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='financeaccesspolicy',
            name='data_scope',
            field=models.CharField(default='Department', max_length=40),
        ),
        migrations.AddField(
            model_name='financeaccesspolicy',
            name='description',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='financeaccesspolicy',
            name='is_protected',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='financeaccesspolicy',
            name='last_reviewed_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financeaccesspolicy',
            name='next_review_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='financeaccesspolicy',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], db_index=True, default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='financeaccesspolicy',
            name='users_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='financeaccesspolicy',
            index=models.Index(fields=['status', 'next_review_date'], name='finance_acc_status_4c4574_idx'),
        ),
    ]
