# Generated by Django 5.2.16 on 2026-07-22 15:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_financeaccesspolicy_approval_limit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='account_type',
            field=models.CharField(default='Current', max_length=40),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='last_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='owner_reference',
            field=models.CharField(blank=True, db_index=True, max_length=180),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='purpose',
            field=models.CharField(db_index=True, default='General', max_length=60),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='verification_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddIndex(
            model_name='bankaccount',
            index=models.Index(fields=['owner_reference', 'is_primary'], name='bank_accoun_owner_r_7c809e_idx'),
        ),
    ]
