# Generated by Django 5.2.16 on 2026-07-14 05:02

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeHRProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('role', models.CharField(max_length=140)),
                ('team', models.CharField(db_index=True, max_length=100)),
                ('manager_name', models.CharField(blank=True, max_length=140)),
                ('location', models.CharField(blank=True, max_length=160)),
                ('employment_type', models.CharField(default='Full-time', max_length=60)),
                ('status', models.CharField(choices=[('active', 'Active'), ('probation', 'Probation'), ('training', 'Training'), ('on_notice', 'On Notice'), ('exited', 'Exited'), ('archived', 'Archived')], db_index=True, default='active', max_length=30)),
                ('health_score', models.PositiveSmallIntegerField(default=75, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('kyc_status', models.CharField(choices=[('complete', 'Complete'), ('pending', 'Pending')], db_index=True, default='pending', max_length=20)),
                ('asset_tag', models.CharField(blank=True, max_length=80)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hr_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'employees',
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField(db_index=True)),
                ('shift', models.CharField(default='10:00 - 19:00', max_length=40)),
                ('check_in', models.TimeField(blank=True, null=True)),
                ('check_out', models.TimeField(blank=True, null=True)),
                ('mode', models.CharField(choices=[('office', 'Office'), ('remote', 'Remote'), ('hybrid', 'Hybrid')], default='office', max_length=20)),
                ('status', models.CharField(choices=[('present', 'Present'), ('late', 'Late'), ('leave', 'Leave'), ('missing_punch', 'Missing Punch'), ('regularized', 'Regularized')], db_index=True, default='regularized', max_length=30)),
                ('billable_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('approval_status', models.CharField(choices=[('auto_approved', 'Auto Approved'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending_approval', max_length=30)),
                ('payroll_impact', models.CharField(choices=[('payable', 'Payable'), ('non_payable', 'Non Payable'), ('review', 'Review')], db_index=True, default='review', max_length=30)),
                ('note', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='hrms.employeehrprofile')),
            ],
            options={
                'db_table': 'attendance',
            },
        ),
        migrations.CreateModel(
            name='ExitRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('exit_type', models.CharField(choices=[('resignation', 'Resignation'), ('termination', 'Termination'), ('contract_end', 'Contract End'), ('retirement', 'Retirement')], max_length=30)),
                ('resignation_date', models.DateField(db_index=True)),
                ('last_day', models.DateField(db_index=True)),
                ('reason', models.TextField()),
                ('notice', models.CharField(choices=[('serving', 'Serving'), ('final_week', 'Final Week'), ('completed', 'Completed')], default='serving', max_length=30)),
                ('handover', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('handover_owner', models.CharField(max_length=140)),
                ('risk', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], db_index=True, default='low', max_length=20)),
                ('laptop_recovered', models.BooleanField(default=False)),
                ('id_card_recovered', models.BooleanField(default=False)),
                ('access_revoked', models.BooleanField(default=False)),
                ('manager_clearance', models.BooleanField(default=False)),
                ('hr_clearance', models.BooleanField(default=False)),
                ('finance_clearance', models.BooleanField(default=False)),
                ('it_clearance', models.BooleanField(default=False)),
                ('ff_status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('cleared', 'Cleared')], db_index=True, default='pending', max_length=30)),
                ('lifecycle_status', models.CharField(choices=[('initiated', 'Initiated'), ('clearance', 'Clearance'), ('ready_for_fnf', 'Ready for F&F'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='initiated', max_length=30)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exit_requests', to='hrms.employeehrprofile')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'exit_requests',
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('leave_type', models.CharField(choices=[('earned_leave', 'Earned Leave'), ('sick_leave', 'Sick Leave'), ('casual_leave', 'Casual Leave'), ('work_from_home', 'Work From Home'), ('comp_off', 'Comp Off')], db_index=True, max_length=30)),
                ('start_date', models.DateField(db_index=True)),
                ('end_date', models.DateField(db_index=True)),
                ('days', models.DecimalField(decimal_places=1, max_digits=5)),
                ('duration', models.CharField(choices=[('full_day', 'Full Day'), ('first_half', 'First Half'), ('second_half', 'Second Half')], default='full_day', max_length=20)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('manager_review', 'Manager Review'), ('hr_review', 'HR Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='manager_review', max_length=30)),
                ('approver', models.CharField(blank=True, max_length=140)),
                ('payroll_impact', models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid'), ('no_impact', 'No Impact')], default='paid', max_length=30)),
                ('applied_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('decision_note', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='hrms.employeehrprofile')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'leave_requests',
            },
        ),
        migrations.CreateModel(
            name='PayrollRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('month', models.CharField(db_index=True, max_length=7)),
                ('basic', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('hra', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('allowance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('conveyance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pf', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pt', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tds', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('advance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('working_days', models.PositiveSmallIntegerField(default=26, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('payable_days', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('lop_days', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('lop_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('readiness', models.CharField(choices=[('ready', 'Ready'), ('attendance_review', 'Attendance Review'), ('leave_review', 'Leave Review')], db_index=True, default='ready', max_length=30)),
                ('hold_reason', models.TextField(blank=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('hr_review', 'HR Review'), ('finance_review', 'Finance Review'), ('approved', 'Approved'), ('paid', 'Paid'), ('hold', 'Hold')], db_index=True, default='draft', max_length=30)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_records', to='hrms.employeehrprofile')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payroll_records',
            },
        ),
        migrations.AddIndex(
            model_name='employeehrprofile',
            index=models.Index(fields=['team', 'status'], name='employees_team_ce5240_idx'),
        ),
        migrations.AddIndex(
            model_name='employeehrprofile',
            index=models.Index(fields=['kyc_status', 'status'], name='employees_kyc_sta_a680b3_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['date', 'status'], name='attendance_date_32df9b_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['employee', 'date'], name='attendance_employe_c9bb2b_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['approval_status', 'payroll_impact'], name='attendance_approva_8a9270_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.UniqueConstraint(fields=('employee', 'date'), name='unique_employee_attendance_date'),
        ),
        migrations.AddIndex(
            model_name='exitrequest',
            index=models.Index(fields=['employee', 'lifecycle_status'], name='exit_reques_employe_182341_idx'),
        ),
        migrations.AddIndex(
            model_name='exitrequest',
            index=models.Index(fields=['last_day', 'risk'], name='exit_reques_last_da_ab9806_idx'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['employee', 'status'], name='leave_reque_employe_fd03a1_idx'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['start_date', 'end_date'], name='leave_reque_start_d_08703b_idx'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['leave_type', 'status'], name='leave_reque_leave_t_1e1969_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollrecord',
            index=models.Index(fields=['month', 'status'], name='payroll_rec_month_267a92_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollrecord',
            index=models.Index(fields=['readiness', 'status'], name='payroll_rec_readine_39031e_idx'),
        ),
        migrations.AddConstraint(
            model_name='payrollrecord',
            constraint=models.UniqueConstraint(fields=('employee', 'month'), name='unique_employee_payroll_month'),
        ),
    ]
