from django.urls import path

from apps.finance.views import (
    ApprovalPolicyDetailView,
    ApprovalPolicyListCreateView,
    BankAccountDetailView,
    BankAccountListCreateView,
    BudgetRevisionDetailView,
    BudgetRevisionListCreateView,
    FinanceAccessPolicyDetailView,
    FinanceAccessPolicyListCreateView,
    FinanceClientDetailView,
    FinanceClientListCreateView,
    FinanceClientSyncView,
    FinanceOverviewView,
    GSTReturnDetailView,
    GSTReturnListCreateView,
    InvoiceActionView,
    InvoiceDetailView,
    InvoiceListCreateView,
    NumberedDetailView,
    NumberedListCreateView,
    PaymentActionView,
    PaymentListCreateView,
    QuotationActionView,
    QuotationDetailView,
    QuotationListCreateView,
    ReminderDetailView,
    ReminderListCreateView,
    VendorDetailView,
    VendorListCreateView,
)

urlpatterns = [
    path("finance/overview/", FinanceOverviewView.as_view(), name="finance-overview"),
    path("finance/clients/", FinanceClientListCreateView.as_view(), name="finance-clients"),
    path("finance/clients/sync-project-client/<uuid:project_client_id>/", FinanceClientSyncView.as_view(), name="finance-client-sync-project-client"),
    path("finance/clients/<uuid:client_id>/", FinanceClientDetailView.as_view(), name="finance-client-detail"),
    path("finance/vendors/", VendorListCreateView.as_view(), name="finance-vendors"),
    path("finance/vendors/<uuid:object_id>/", VendorDetailView.as_view(), name="finance-vendor-detail"),
    path("finance/bank-accounts/", BankAccountListCreateView.as_view(), name="finance-bank-accounts"),
    path("finance/bank-accounts/<uuid:object_id>/", BankAccountDetailView.as_view(), name="finance-bank-account-detail"),
    path("finance/quotations/", QuotationListCreateView.as_view(), name="finance-quotations"),
    path("finance/quotations/<uuid:quotation_id>/", QuotationDetailView.as_view(), name="finance-quotation-detail"),
    path("finance/quotations/<uuid:quotation_id>/action/", QuotationActionView.as_view(), name="finance-quotation-action"),
    path("finance/invoices/", InvoiceListCreateView.as_view(), name="finance-invoices"),
    path("finance/invoices/<uuid:invoice_id>/", InvoiceDetailView.as_view(), name="finance-invoice-detail"),
    path("finance/invoices/<uuid:invoice_id>/action/", InvoiceActionView.as_view(), name="finance-invoice-action"),
    path("finance/payments/", PaymentListCreateView.as_view(), name="finance-payments"),
    path("finance/payments/<uuid:payment_id>/action/", PaymentActionView.as_view(), name="finance-payment-action"),
    path("finance/reminders/", ReminderListCreateView.as_view(), name="finance-reminders"),
    path("finance/reminders/<uuid:object_id>/", ReminderDetailView.as_view(), name="finance-reminder-detail"),
    path("finance/budget-revisions/", BudgetRevisionListCreateView.as_view(), name="finance-budget-revisions"),
    path("finance/budget-revisions/<uuid:object_id>/", BudgetRevisionDetailView.as_view(), name="finance-budget-revision-detail"),
    path("finance/gst-returns/", GSTReturnListCreateView.as_view(), name="finance-gst-returns"),
    path("finance/gst-returns/<uuid:object_id>/", GSTReturnDetailView.as_view(), name="finance-gst-return-detail"),
    path("finance/approval-policies/", ApprovalPolicyListCreateView.as_view(), name="finance-approval-policies"),
    path("finance/approval-policies/<uuid:object_id>/", ApprovalPolicyDetailView.as_view(), name="finance-approval-policy-detail"),
    path("finance/access-policies/", FinanceAccessPolicyListCreateView.as_view(), name="finance-access-policies"),
    path("finance/access-policies/<uuid:object_id>/", FinanceAccessPolicyDetailView.as_view(), name="finance-access-policy-detail"),
    path("finance/<str:resource>/", NumberedListCreateView.as_view(), name="finance-numbered-resource"),
    path("finance/<str:resource>/<uuid:object_id>/", NumberedDetailView.as_view(), name="finance-numbered-resource-detail"),
]
