# Generated by Django 5.2.16 on 2026-07-10 05:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('lead_number', models.CharField(max_length=40, unique=True)),
                ('lead_type', models.CharField(choices=[('project', 'Project'), ('trading', 'Trading')], db_index=True, default='project', max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('proposal', 'Proposal'), ('won', 'Won'), ('lost', 'Lost')], db_index=True, default='new', max_length=30)),
                ('source', models.CharField(blank=True, db_index=True, max_length=80)),
                ('company_name', models.CharField(blank=True, db_index=True, max_length=180)),
                ('contact_name', models.CharField(max_length=160)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('mobile', models.CharField(db_index=True, max_length=20)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('requirement_summary', models.TextField(blank=True)),
                ('estimated_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'leads',
                'indexes': [models.Index(fields=['lead_number'], name='leads_lead_nu_3df04f_idx'), models.Index(fields=['status', 'lead_type'], name='leads_status_9293fe_idx'), models.Index(fields=['mobile', 'email'], name='leads_mobile_a24136_idx'), models.Index(fields=['company_name'], name='leads_company_fd5a90_idx')],
            },
        ),
    ]
