# Generated by Django 5.2.16 on 2026-07-12 02:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_leadfollowup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectClient',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('client_number', models.CharField(max_length=40, unique=True)),
                ('company_name', models.CharField(db_index=True, max_length=180)),
                ('project_name', models.CharField(max_length=220)),
                ('project_type', models.CharField(blank=True, max_length=120)),
                ('project_status', models.CharField(choices=[('discovery', 'Discovery'), ('development', 'Development'), ('uat', 'UAT'), ('agreement_pending', 'Agreement Pending')], default='discovery', max_length=30)),
                ('project_owner', models.CharField(blank=True, max_length=160)),
                ('team_leader', models.CharField(blank=True, max_length=160)),
                ('telecaller', models.CharField(blank=True, max_length=160)),
                ('agreement_status', models.CharField(choices=[('pending', 'Pending'), ('drafted', 'Drafted'), ('signed', 'Signed')], default='pending', max_length=30)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('next_action', models.CharField(blank=True, max_length=240)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('source_lead', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_client', to='crm.lead')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'project_clients',
            },
        ),
        migrations.CreateModel(
            name='ClientContact',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('role', models.CharField(choices=[('decision_maker', 'Decision Maker'), ('technical', 'Technical'), ('finance', 'Finance'), ('daily_coordinator', 'Daily Coordinator')], default='decision_maker', max_length=30)),
                ('name', models.CharField(max_length=160)),
                ('designation', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('responsibility', models.CharField(blank=True, max_length=240)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='crm.projectclient')),
            ],
            options={
                'db_table': 'client_contacts',
            },
        ),
        migrations.CreateModel(
            name='ProjectHandoff',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('project_code', models.CharField(max_length=40, unique=True)),
                ('project_manager', models.CharField(max_length=160)),
                ('start_date', models.DateField()),
                ('target_end_date', models.DateField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='high', max_length=20)),
                ('billing_model', models.CharField(max_length=80)),
                ('delivery_method', models.CharField(max_length=80)),
                ('communication_channel', models.CharField(blank=True, max_length=160)),
                ('repository_url', models.URLField(blank=True)),
                ('kickoff_notes', models.TextField()),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('active', 'Active'), ('on_hold', 'On Hold'), ('completed', 'Completed')], default='planning', max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_handoffs', to='crm.projectclient')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'project_handoffs',
            },
        ),
        migrations.AddIndex(
            model_name='projectclient',
            index=models.Index(fields=['client_number'], name='project_cli_client__61cddb_idx'),
        ),
        migrations.AddIndex(
            model_name='projectclient',
            index=models.Index(fields=['company_name'], name='project_cli_company_f402f7_idx'),
        ),
        migrations.AddIndex(
            model_name='projectclient',
            index=models.Index(fields=['agreement_status', 'project_status'], name='project_cli_agreeme_6a80ac_idx'),
        ),
        migrations.AddIndex(
            model_name='clientcontact',
            index=models.Index(fields=['client', 'role'], name='client_cont_client__a572f6_idx'),
        ),
        migrations.AddIndex(
            model_name='clientcontact',
            index=models.Index(fields=['phone', 'email'], name='client_cont_phone_68ebfe_idx'),
        ),
        migrations.AddIndex(
            model_name='projecthandoff',
            index=models.Index(fields=['project_code'], name='project_han_project_1a012e_idx'),
        ),
        migrations.AddIndex(
            model_name='projecthandoff',
            index=models.Index(fields=['status', 'priority'], name='project_han_status_0fcd2e_idx'),
        ),
        migrations.AddIndex(
            model_name='projecthandoff',
            index=models.Index(fields=['start_date', 'target_end_date'], name='project_han_start_d_2ed97c_idx'),
        ),
    ]
