# Generated by Django 5.2.16 on 2026-07-12 03:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_projectclient_clientcontact_projecthandoff_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectAgreement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('agreement_number', models.CharField(max_length=40, unique=True)),
                ('agreement_type', models.CharField(choices=[('msa', 'Master Service Agreement'), ('sow', 'Statement of Work'), ('nda', 'Non-Disclosure Agreement'), ('sla', 'Service Level Agreement')], default='msa', max_length=30)),
                ('effective_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('contract_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('payment_terms', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('under_review', 'Under Review'), ('sent_for_signature', 'Sent for Signature'), ('active', 'Active'), ('expired', 'Expired'), ('terminated', 'Terminated')], db_index=True, default='draft', max_length=30)),
                ('remarks', models.TextField(blank=True)),
                ('attachment_name', models.CharField(blank=True, max_length=240)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='crm.projectclient')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('project_handoff', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agreement', to='crm.projecthandoff')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'project_agreements',
                'indexes': [models.Index(fields=['agreement_number'], name='project_agr_agreeme_242269_idx'), models.Index(fields=['status', 'agreement_type'], name='project_agr_status_cb8012_idx'), models.Index(fields=['effective_date', 'expiry_date'], name='project_agr_effecti_d1a49b_idx')],
            },
        ),
    ]
