# Generated by Django 5.2.16 on 2026-07-24 05:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadSource',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('source_code', models.CharField(max_length=20, unique=True)),
                ('source', models.CharField(db_index=True, max_length=180)),
                ('source_type', models.CharField(choices=[('Organic', 'Organic'), ('Paid', 'Paid'), ('Referral', 'Referral'), ('Outbound', 'Outbound'), ('Event', 'Event'), ('Partner', 'Partner'), ('Offline', 'Offline')], db_index=True, max_length=20)),
                ('normalized_key', models.CharField(db_index=True, max_length=120, unique=True)),
                ('default_utm_source', models.CharField(max_length=120)),
                ('default_utm_medium', models.CharField(max_length=120)),
                ('owner', models.CharField(db_index=True, max_length=160)),
                ('quality', models.CharField(choices=[('High', 'High'), ('High Intent', 'High Intent'), ('Enterprise', 'Enterprise'), ('Warm', 'Warm'), ('Mixed', 'Mixed'), ('Nurture', 'Nurture'), ('Low', 'Low')], db_index=True, max_length=40)),
                ('leads', models.PositiveIntegerField(default=0)),
                ('mql', models.PositiveIntegerField(default=0)),
                ('sql', models.PositiveIntegerField(default=0)),
                ('won', models.PositiveIntegerField(default=0)),
                ('last_30_change', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Review', 'Review'), ('Paused', 'Paused'), ('Archived', 'Archived')], db_index=True, default='Active', max_length=20)),
                ('next_action', models.CharField(max_length=240)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lead_sources',
                'indexes': [models.Index(fields=['source_code'], name='lead_source_source__e6d5db_idx'), models.Index(fields=['source_type', 'status'], name='lead_source_source__a14308_idx'), models.Index(fields=['quality', 'status'], name='lead_source_quality_51db33_idx'), models.Index(fields=['owner', 'status'], name='lead_source_owner_0c9ca9_idx')],
            },
        ),
        migrations.CreateModel(
            name='MarketingCampaign',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('campaign_code', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(db_index=True, max_length=180)),
                ('channel', models.CharField(choices=[('Google Search', 'Google Search'), ('LinkedIn Ads', 'LinkedIn Ads'), ('Meta Ads', 'Meta Ads'), ('WhatsApp', 'WhatsApp'), ('Email', 'Email'), ('Webinar', 'Webinar'), ('Marketplace', 'Marketplace')], db_index=True, max_length=40)),
                ('objective', models.CharField(max_length=220)),
                ('audience_segment', models.CharField(max_length=220)),
                ('budget_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('spent_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('leads', models.PositiveIntegerField(default=0)),
                ('mql', models.PositiveIntegerField(default=0)),
                ('pipeline_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('start_date', models.DateField(db_index=True)),
                ('end_date', models.DateField(db_index=True)),
                ('utm_source', models.CharField(db_index=True, max_length=120)),
                ('utm_medium', models.CharField(db_index=True, max_length=120)),
                ('utm_campaign', models.CharField(db_index=True, max_length=160, unique=True)),
                ('landing_page', models.CharField(max_length=240)),
                ('lead_form', models.CharField(max_length=180)),
                ('owner', models.CharField(db_index=True, max_length=160)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Review', 'Review'), ('Scale', 'Scale'), ('Archived', 'Archived')], db_index=True, default='Draft', max_length=20)),
                ('next_action', models.CharField(max_length=240)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'marketing_campaigns',
                'indexes': [models.Index(fields=['campaign_code'], name='marketing_c_campaig_8ec8ee_idx'), models.Index(fields=['status', 'channel'], name='marketing_c_status_39f9b7_idx'), models.Index(fields=['owner', 'status'], name='marketing_c_owner_0da97d_idx'), models.Index(fields=['start_date', 'end_date'], name='marketing_c_start_d_6d1813_idx')],
            },
        ),
    ]
